### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by metaton8086** [dotfortun3-code/homebridge-infinitude-v2#14]
I updated from the original homebridge-infinitude to V2 and it gives me the errors below:

**1st Error**

[5/14/2023, 8:45:02 AM] [homebridge-infinitude-v2] [VERBOSE] Retrieving from api http://192.168.10.2:3000/api/status/zones
[5/14/2023, 8:45:02 AM] [homebridge-infinitude-v2] Platform initialized.
[5/14/2023, 8:45:02 AM] [homebridge-infinitude-v2] Error: timeout of 5000ms exceeded
    at createError (/homebridge/node_modules/homebridge-infinitude-v2/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/homebridge/node_modules/homebridge-infinitude-v2/node_modules/axios/lib/adapters/http.js:303:16)
    at RedirectableRequest.emit (node:events:513:28)
    at Timeout.<anonymous> (/homebridge/node_modules/homebridge-infinitude-v2/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7) {
  config: {
    url: 'http://192.168.10.2:3000/api/status/zones',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 5000,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  code: 'ECONNABORTED',
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: destroyOnTimeout]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '/api/status/zones',
      method: 'GET',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: '192.168.10.2',
      port: '3000',
      nativeProtocols: [Object],
      pathname: '/api/status/zones'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /api/status/zones HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'Host: 192.168.10.2:3000\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/status/zones',
      _ended: false,
      res: null,
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.10.2',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null,
      [Symbol(kError)]: undefined
    },
    _currentUrl: 'http://192.168.10.2:3000/api/status/zones',
    _timeout: null,
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
TypeError: Cannot read properties of undefined (reading 'data')
    at /homebridge/node_modules/homebridge-infinitude-v2/src/InfinitudeClient.js:79:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:533:9)
    at processTimers (node:internal/timers:507:7)

**Second Error**

[5/14/2023, 8:45:11 AM] [homebridge-infinitude-v2] [VERBOSE] /api/status/zones response: {"zones":{"zone":[{"clsp":["73.0"],"currentActivity":["manual"],"damperposition":["0"],"enabled":["on"],"fan":["off"],"hold":["on"],"htsp":["66.0"],"id":"1","name":["Living Room"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":["69.0"],"zoneconditioning":["idle"]},{"clsp":["73.0"],"currentActivity":["manual"],"damperposition":["15"],"enabled":["on"],"fan":["off"],"hold":["on"],"htsp":["66.0"],"id":"2","name":["Master Bedroom"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":["68.0"],"zoneconditioning":["idle"]},{"clsp":["80.0"],"currentActivity":["away"],"damperposition":["0"],"enabled":["off"],"fan":["off"],"hold":["off"],"htsp":["60.0"],"id":"3","name":["Zone 3"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":[{}],"zoneconditioning":["idle"]},{"clsp":["80.0"],"currentActivity":["away"],"damperposition":["0"],"enabled":["off"],"fan":["off"],"hold":["off"],"htsp":["60.0"],"id":"4","name":["Zone 4"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":[{}],"zoneconditioning":["idle"]},{"clsp":["80.0"],"currentActivity":["away"],"damperposition":["0"],"enabled":["off"],"fan":["off"],"hold":["off"],"htsp":["60.0"],"id":"5","name":["Zone 5"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":[{}],"zoneconditioning":["idle"]},{"clsp":["80.0"],"currentActivity":["away"],"damperposition":["0"],"enabled":["off"],"fan":["off"],"hold":["off"],"htsp":["60.0"],"id":"6","name":["Zone 6"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":[{}],"zoneconditioning":["idle"]},{"clsp":["80.0"],"currentActivity":["away"],"damperposition":["0"],"enabled":["off"],"fan":["off"],"hold":["off"],"htsp":["60.0"],"id":"7","name":["Zone 7"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":[{}],"zoneconditioning":["idle"]},{"clsp":["80.0"],"currentActivity":["away"],"damperposition":["0"],"enabled":["off"],"fan":["off"],"hold":["off"],"htsp":["60.0"],"id":"8","name":["Zone 8"],"occupancy":["unoccupied"],"occupancyOverride":["off"],"otmr":[{}],"rh":["44"],"rt":[{}],"zoneconditioning":["idle"]}]}} 
TypeError: Cannot read properties of undefined (reading 'name')
    at getRoombas (/homebridge/node_modules/homebridge-irobot/src/getRoombas.ts:50:63)
    at iRobotPlatform.discoverDevices (/homebridge/node_modules/homebridge-irobot/src/platform.ts:65:36)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-irobot/src/platform.ts:34:12)
    at HomebridgeAPI.emit (node:events:513:28)
    at HomebridgeAPI.signalFinished (/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:189:14)

**Comment by metaton8086** [comment]
This may not actually be an issue.  Running this outside of a child bridge seems to work fine.  I think it is due to the child bridge having a the port not defined on the podman container.
